[[redirects]]
  from = "/api/*"
  to = "https://realestate-marketplace.up.railway.app/api/:splat"
  status = 200
  force = true

  [[headers]]
    for = "/api/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://reale-state-website.netlify.app"
      Access-Control-Allow-Credentials = "true"
